### PR TITLE
chore: adds v2 architecture diagrams to assets/

### PR DESCRIPTION
**Pull request by askmeegs**

### CODE REVIEW

**Review by NimJay — CHANGES_REQUESTED** [review]
Thank you so much for helping out here, @askmeegs!

This repo is used for two JSSes:
* [dynamic-web-app](https://console.cloud.google.com/products/solutions/details/dynamic-web-app)
* [ecommerce-platform-serverless](https://pantheon.corp.google.com/products/solutions/details/ecommerce-platform-serverless)

I'm not sure if the architecture is equivalent between the two JSSes.
If they **are not**, the files should look like:
```
/assets/architecture-dynamic-web-app.json
/assets/architecture-dynamic-web-app.png
/assets/architecture-dynamic-web-app.svg
/assets/architecture-ecommerce-platform-serverless.json
/assets/architecture-ecommerce-platform-serverless.png
/assets/architecture-ecommerce-platform-serverless.svg
```

If they _are_ equivalent, I approve.

Context for others: [go/jss-diagrams](http://go/jss-diagrams) details the process for JSS diagram maintenance.

**Review by NimJay — APPROVED** [review]
Looks great!

**Review by grayside — APPROVED** [review]

**Comment by grayside** [comment]
This is failing because the linter wants an empty line at the end of the JSON file. I attempted to suggest that via comment, but the size of the file as a one-line JSON happened to trigger a memory crash.

Would it be possible to format the JSON via `jq` or similar for ease of maintenance?

**Pull request merged**
