### PR TITLE
feat: test suffix and non-suffix variations

### PR DESCRIPTION
**Pull request by glasnt**
By default, `random_suffix` is true, meaning all elements are created with `-nnnn`. 

We should also ensure we test the single deployment-per-project option. 

simple_example: no suffix
suffix_example: random suffixes

### CODE REVIEW

**Comment by glasnt** [comment]
re: [bc5e861](https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/pull/59/commits/bc5e8615eb24f711f106bb8b4de4bee5d20e6472)

I borrowed from https://github.com/GoogleCloudPlatform/terraform-google-secure-cicd/blob/main/build/int.cloudbuild.yaml#L31 to run the multiple tests, but unsure why there's `waitFor`s that appear to only be in series, so trying without those for now.

**Comment by glasnt** [comment]
This can't be merged until #58, as I don't believe the TF will succeed without it.

**Comment by grayside** [comment]
waitFor in sequence is the same as no waitFor at all. However, looking closer at the terraform-google-secure-cicd config,

* everything waits for init-all to complete
* then there are two tracks that run in parallel:
  * Track 1: Sequentially: app_cicd, cloudbuild_private_pool, private_cluster_cicd
  * Track 2: standalone_single_project

Looking at the [docs for waitFor](https://cloud.google.com/build/docs/configuring-builds/configure-build-step-order):
> If no values are provided for waitFor, the build step waits for all prior build steps in the build request to complete successfully before running.

On that basis, most of the `waitFor` configs could be removed, however if the "standalone_single_project" section were moved up in the file, it would break the parallelization of the build.

**Comment by glasnt** [comment]
This will be merged into #58, for testing completeness.

**Pull request closed without merging**
