### PR TITLE
testing: single config for region

### PR DESCRIPTION
**Pull request by grayside**
BEGIN_COMMIT_OVERRIDE
chore(testing): Enable Google Cloud region override via GOOGLE_CLOUD_REGION environment variable
docs: Add region variable to example modules
END_COMMIT_OVERRIDE

### CODE REVIEW

**Comment by grayside** [comment]
This is failing because `region` is not available in the root "example" modules. I will add those in a separate PR, because I think controlling deployment region is worth including in the example in addition to enabling this testing improvement.

**Comment by glasnt** [comment]
@grayside can this draft PR be closed?

**Comment by grayside** [comment]
Build c771a4e8-38e3-410c-88a5-54d5a73ad529 demonstrates the override of region via environment variable working. Now under test, converting the temporary config to commented out usage documentation on how to override the region.

**Review by glasnt — APPROVED** [review]

**Pull request merged**
